version: '3.8'

services:
  test:
    image: test-image:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: test-container
    ports:
      - "9003:9003"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge